apiVersion: v1
kind: Service
metadata:
  name: {{ include "bind9-dns.fullname" . }}
  labels:
    {{- include "bind9-dns.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.tcpPort }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.service.udpPort }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "bind9-dns.selectorLabels" . | nindent 4 }}
